-- CREATE DATABASE
DROP DATABASE IF EXISTS cooking;
CREATE DATABASE cooking CHARACTER SET 'utf8';

-- DEFINED THE DATABASE THAT WE WILL WORK ON IT
USE cooking;

-- CHECK IF THE TABLE EXIST
DROP TABLE IF EXISTS recipes;

CREATE TABLE recipe(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(64),
	img_path TEXT,
	country TEXT,
	UNIQUE(name)
);

CREATE TABLE detail(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ingredient TEXT,
	step TEXT,
	duration INT,
	recipeID INT
);

COMMIT;